import { openDatabase } from "../database";
import {
    ExamQuestion,
    saveDownloadedDocument,
    saveDownloadedVideo,
    saveExamQuestions,
} from "./downloads";

export async function seedMockData(): Promise<void> {
  const db = await openDatabase();

  // ตรวจว่ามีข้อมูล seed แล้วหรือยัง
  const existing = await db.getFirstAsync<{ count: number }>(
    `SELECT COUNT(*) as count FROM downloaded_videos`,
  );
  if ((existing?.count ?? 0) > 0) return;

  // ===== VDO mock data =====
  const videos = [
    {
      video_id: "math_vid_1",
      title: "คณิตศาสตร์ - บทที่ 1: เลขยกกำลัง",
      subject_id: "math",
      subject_name: "คณิตศาสตร์",
      grade: "m5",
      thumbnail_url: "https://picsum.photos/seed/math1/400/225",
      duration: 1800,
      watch_progress: 65,
    },
    {
      video_id: "math_vid_2",
      title: "คณิตศาสตร์ - บทที่ 2: ลอการิทึม",
      subject_id: "math",
      subject_name: "คณิตศาสตร์",
      grade: "m5",
      thumbnail_url: "https://picsum.photos/seed/math2/400/225",
      duration: 2400,
      watch_progress: 30,
    },
    {
      video_id: "math_vid_3",
      title: "คณิตศาสตร์ - บทที่ 3: ตรีโกณมิติ",
      subject_id: "math",
      subject_name: "คณิตศาสตร์",
      grade: "m5",
      thumbnail_url: "https://picsum.photos/seed/math3/400/225",
      duration: 2700,
      watch_progress: 0,
    },
    {
      video_id: "physics_vid_1",
      title: "ฟิสิกส์ - บทที่ 1: การเคลื่อนที่",
      subject_id: "physics",
      subject_name: "ฟิสิกส์",
      grade: "m5",
      thumbnail_url: "https://picsum.photos/seed/physics1/400/225",
      duration: 2100,
      watch_progress: 100,
    },
    {
      video_id: "physics_vid_2",
      title: "ฟิสิกส์ - บทที่ 2: แรงและกฎนิวตัน",
      subject_id: "physics",
      subject_name: "ฟิสิกส์",
      grade: "m5",
      thumbnail_url: "https://picsum.photos/seed/physics2/400/225",
      duration: 1920,
      watch_progress: 50,
    },
    {
      video_id: "thai_vid_1",
      title: "ภาษาไทย - บทที่ 1: การอ่านวรรณคดี",
      subject_id: "thai",
      subject_name: "ภาษาไทย",
      grade: "m3",
      thumbnail_url: "https://picsum.photos/seed/thai1/400/225",
      duration: 1500,
      watch_progress: 80,
    },
    {
      video_id: "english_vid_1",
      title: "ภาษาอังกฤษ - Unit 1: Greetings",
      subject_id: "english",
      subject_name: "ภาษาอังกฤษ",
      grade: "m1",
      thumbnail_url: "https://picsum.photos/seed/english1/400/225",
      duration: 1200,
      watch_progress: 20,
    },
  ];

  for (const v of videos) {
    await saveDownloadedVideo(v);
  }

  // ===== Documents mock data =====
  const documents = [
    {
      doc_id: "m5_math_doc_1",
      title: "เอกสารประกอบ: เลขยกกำลัง",
      subject_id: "math",
      subject_name: "คณิตศาสตร์",
      grade: "m5",
      doc_type: "pdf" as const,
    },
    {
      doc_id: "m5_math_doc_2",
      title: "เอกสารประกอบ: ลอการิทึม",
      subject_id: "math",
      subject_name: "คณิตศาสตร์",
      grade: "m5",
      doc_type: "pdf" as const,
    },
    {
      doc_id: "m5_math_doc_3",
      title: "สรุปสูตร ตรีโกณมิติ",
      subject_id: "math",
      subject_name: "คณิตศาสตร์",
      grade: "m5",
      doc_type: "pdf" as const,
    },
    {
      doc_id: "m5_physics_doc_1",
      title: "เอกสารประกอบ: การเคลื่อนที่",
      subject_id: "physics",
      subject_name: "ฟิสิกส์",
      grade: "m5",
      doc_type: "pdf" as const,
    },
    {
      doc_id: "m5_physics_doc_2",
      title: "เอกสารประกอบ: แรงและกฎนิวตัน",
      subject_id: "physics",
      subject_name: "ฟิสิกส์",
      grade: "m5",
      doc_type: "pdf" as const,
    },
    {
      doc_id: "m3_thai_doc_1",
      title: "เอกสารประกอบ: วรรณคดีไทย",
      subject_id: "thai",
      subject_name: "ภาษาไทย",
      grade: "m3",
      doc_type: "pdf" as const,
    },
    {
      doc_id: "m1_english_doc_1",
      title: "Worksheet: Unit 1 Greetings",
      subject_id: "english",
      subject_name: "ภาษาอังกฤษ",
      grade: "m1",
      doc_type: "pdf" as const,
    },
  ];

  for (const doc of documents) {
    await saveDownloadedDocument(doc);
  }

  // ===== Exam Questions mock data =====
  const mathExam: ExamQuestion[] = [
    {
      exam_id: "m5_math_exam_1",
      subject_id: "math",
      subject_name: "คณิตศาสตร์",
      grade: "m5",
      question: "2³ × 2⁴ มีค่าเท่าใด?",
      choice_a: "2⁷",
      choice_b: "2¹²",
      choice_c: "4⁷",
      choice_d: "2⁶",
      answer: "A",
      explanation:
        "กฎการคูณเลขยกกำลัง: aᵐ × aⁿ = aᵐ⁺ⁿ ดังนั้น 2³ × 2⁴ = 2³⁺⁴ = 2⁷",
    },
    {
      exam_id: "m5_math_exam_1",
      subject_id: "math",
      subject_name: "คณิตศาสตร์",
      grade: "m5",
      question: "(3²)³ มีค่าเท่าใด?",
      choice_a: "3⁵",
      choice_b: "3⁶",
      choice_c: "3⁸",
      choice_d: "9⁶",
      answer: "B",
      explanation: "กฎการยกกำลังซ้อน: (aᵐ)ⁿ = aᵐⁿ ดังนั้น (3²)³ = 3²ˣ³ = 3⁶",
    },
    {
      exam_id: "m5_math_exam_1",
      subject_id: "math",
      subject_name: "คณิตศาสตร์",
      grade: "m5",
      question: "log₂(8) มีค่าเท่าใด?",
      choice_a: "2",
      choice_b: "4",
      choice_c: "3",
      choice_d: "8",
      answer: "C",
      explanation: "log₂(8) = log₂(2³) = 3 เพราะ 2³ = 8",
    },
    {
      exam_id: "m5_math_exam_1",
      subject_id: "math",
      subject_name: "คณิตศาสตร์",
      grade: "m5",
      question: "sin(30°) มีค่าเท่าใด?",
      choice_a: "√3/2",
      choice_b: "1/2",
      choice_c: "√2/2",
      choice_d: "1",
      answer: "B",
      explanation: "sin(30°) = 1/2 เป็นค่าตรีโกณมิติมาตรฐาน",
    },
    {
      exam_id: "m5_math_exam_1",
      subject_id: "math",
      subject_name: "คณิตศาสตร์",
      grade: "m5",
      question: "sin²θ + cos²θ เท่ากับเท่าใด?",
      choice_a: "0",
      choice_b: "2",
      choice_c: "sin(2θ)",
      choice_d: "1",
      answer: "D",
      explanation: "เป็นเอกลักษณ์ตรีโกณมิติพื้นฐาน sin²θ + cos²θ = 1 เสมอ",
    },
  ];

  const physicsExam: ExamQuestion[] = [
    {
      exam_id: "m5_physics_exam_1",
      subject_id: "physics",
      subject_name: "ฟิสิกส์",
      grade: "m5",
      question:
        "วัตถุเคลื่อนที่สม่ำเสมอ ความเร็ว 10 m/s ใน 5 วินาที เคลื่อนที่ได้กี่เมตร?",
      choice_a: "2 m",
      choice_b: "50 m",
      choice_c: "15 m",
      choice_d: "500 m",
      answer: "B",
      explanation: "ระยะทาง = ความเร็ว × เวลา = 10 × 5 = 50 เมตร",
    },
    {
      exam_id: "m5_physics_exam_1",
      subject_id: "physics",
      subject_name: "ฟิสิกส์",
      grade: "m5",
      question: "กฎการเคลื่อนที่ข้อที่ 2 ของนิวตันคืออะไร?",
      choice_a: "F = ma",
      choice_b: "F = mv",
      choice_c: "F = mg",
      choice_d: "F = m/a",
      answer: "A",
      explanation: "กฎข้อสองของนิวตัน: แรงลัพธ์ = มวล × ความเร่ง (F = ma)",
    },
    {
      exam_id: "m5_physics_exam_1",
      subject_id: "physics",
      subject_name: "ฟิสิกส์",
      grade: "m5",
      question: "วัตถุหนัก 5 kg รับแรง 20 N ความเร่งเท่าใด?",
      choice_a: "4 m/s²",
      choice_b: "100 m/s²",
      choice_c: "25 m/s²",
      choice_d: "0.25 m/s²",
      answer: "A",
      explanation: "a = F/m = 20/5 = 4 m/s²",
    },
    {
      exam_id: "m5_physics_exam_1",
      subject_id: "physics",
      subject_name: "ฟิสิกส์",
      grade: "m5",
      question: "ความเร่งโน้มถ่วงของโลกมีค่าประมาณเท่าใด?",
      choice_a: "9.8 m/s²",
      choice_b: "10.8 m/s²",
      choice_c: "6.7 m/s²",
      choice_d: "8.9 m/s²",
      answer: "A",
      explanation: "g ≈ 9.8 m/s² (มักใช้ 10 m/s² ในการคำนวณ)",
    },
    {
      exam_id: "m5_physics_exam_1",
      subject_id: "physics",
      subject_name: "ฟิสิกส์",
      grade: "m5",
      question: "วัตถุนิ่งหรือเคลื่อนที่สม่ำเสมอ แสดงว่าแรงลัพธ์เท่าใด?",
      choice_a: "มีค่าสูงสุด",
      choice_b: "เท่ากับแรงโน้มถ่วง",
      choice_c: "เท่ากับศูนย์",
      choice_d: "มีค่าคงที่",
      answer: "C",
      explanation:
        "กฎข้อหนึ่งของนิวตัน: ถ้าแรงลัพธ์ = 0 วัตถุจะนิ่งหรือเคลื่อนที่สม่ำเสมอ",
    },
  ];

  const thaiExam: ExamQuestion[] = [
    {
      exam_id: "m3_thai_exam_1",
      subject_id: "thai",
      subject_name: "ภาษาไทย",
      grade: "m3",
      question: "วรรณคดีเรื่องใดแต่งโดยสุนทรภู่?",
      choice_a: "รามเกียรติ์",
      choice_b: "พระอภัยมณี",
      choice_c: "ขุนช้างขุนแผน",
      choice_d: "อิเหนา",
      answer: "B",
      explanation: "พระอภัยมณีแต่งโดยสุนทรภู่ กวีเอกแห่งรัตนโกสินทร์",
    },
    {
      exam_id: "m3_thai_exam_1",
      subject_id: "thai",
      subject_name: "ภาษาไทย",
      grade: "m3",
      question: "คำประพันธ์ประเภทใดใช้สัมผัสนอกและสัมผัสใน?",
      choice_a: "ร่ายสุภาพ",
      choice_b: "โคลงสี่สุภาพ",
      choice_c: "กลอนสุภาพ",
      choice_d: "กาพย์ยานี",
      answer: "C",
      explanation: "กลอนสุภาพมีสัมผัสนอกและสัมผัสในที่ชัดเจน",
    },
    {
      exam_id: "m3_thai_exam_1",
      subject_id: "thai",
      subject_name: "ภาษาไทย",
      grade: "m3",
      question: "ข้อใดเป็นสระเดี่ยว?",
      choice_a: "เอีย",
      choice_b: "อัว",
      choice_c: "อา",
      choice_d: "เอือ",
      answer: "C",
      explanation: "อา เป็นสระเดี่ยว ส่วน เอีย อัว เอือ เป็นสระประสม",
    },
    {
      exam_id: "m3_thai_exam_1",
      subject_id: "thai",
      subject_name: "ภาษาไทย",
      grade: "m3",
      question: "ข้อใดเขียนถูกต้อง?",
      choice_a: "กะทัดรัด",
      choice_b: "กระทัดรัด",
      choice_c: "กระทัตรัด",
      choice_d: "กะทัตรัด",
      answer: "B",
      explanation: "เขียนถูกต้องคือ กระทัดรัด",
    },
    {
      exam_id: "m3_thai_exam_1",
      subject_id: "thai",
      subject_name: "ภาษาไทย",
      grade: "m3",
      question: "คำว่า 'มหา' มาจากภาษาใด?",
      choice_a: "เขมร",
      choice_b: "จีน",
      choice_c: "บาลี-สันสกฤต",
      choice_d: "อังกฤษ",
      answer: "C",
      explanation: "มหา มาจากภาษาบาลี-สันสกฤต แปลว่า ใหญ่ หรือ ยิ่งใหญ่",
    },
  ];

  const englishExam: ExamQuestion[] = [
    {
      exam_id: "m1_english_exam_1",
      subject_id: "english",
      subject_name: "ภาษาอังกฤษ",
      grade: "m1",
      question: "Which greeting is used in the morning?",
      choice_a: "Good evening",
      choice_b: "Good night",
      choice_c: "Good morning",
      choice_d: "Good afternoon",
      answer: "C",
      explanation:
        "'Good morning' is used to greet someone in the morning (before noon).",
    },
    {
      exam_id: "m1_english_exam_1",
      subject_id: "english",
      subject_name: "ภาษาอังกฤษ",
      grade: "m1",
      question: "What is the correct response to 'How are you?'",
      choice_a: "I am 13 years old.",
      choice_b: "I am fine, thank you.",
      choice_c: "My name is Tom.",
      choice_d: "I am from Thailand.",
      answer: "B",
      explanation:
        "The standard response to 'How are you?' is 'I am fine, thank you.'",
    },
    {
      exam_id: "m1_english_exam_1",
      subject_id: "english",
      subject_name: "ภาษาอังกฤษ",
      grade: "m1",
      question: "Which word means the same as 'Hello'?",
      choice_a: "Goodbye",
      choice_b: "Sorry",
      choice_c: "Hi",
      choice_d: "Please",
      answer: "C",
      explanation: "'Hi' is an informal way of saying 'Hello'.",
    },
    {
      exam_id: "m1_english_exam_1",
      subject_id: "english",
      subject_name: "ภาษาอังกฤษ",
      grade: "m1",
      question: "Complete: 'My name ___ Tom.'",
      choice_a: "am",
      choice_b: "are",
      choice_c: "is",
      choice_d: "be",
      answer: "C",
      explanation: "Use 'is' with third person singular (he/she/it/name).",
    },
    {
      exam_id: "m1_english_exam_1",
      subject_id: "english",
      subject_name: "ภาษาอังกฤษ",
      grade: "m1",
      question: "What does 'Nice to meet you' mean in Thai?",
      choice_a: "สวัสดีตอนเช้า",
      choice_b: "ยินดีที่ได้รู้จัก",
      choice_c: "ขอบคุณมาก",
      choice_d: "แล้วพบกันใหม่",
      answer: "B",
      explanation:
        "'Nice to meet you' แปลว่า ยินดีที่ได้รู้จัก ใช้เมื่อพบกันครั้งแรก",
    },
  ];

  await saveExamQuestions(mathExam);
  await saveExamQuestions(physicsExam);
  await saveExamQuestions(thaiExam);
  await saveExamQuestions(englishExam);
}
